services:
  # please make sure to run the following command before running the docker-compose up
  # chmod +x merge_policies.sh
  # ./merge_policies.sh
  reearth-cerbos:
    image: ghcr.io/cerbos/cerbos:0.36.0
    ports:
      - 3592:3592
      - 3593:3593
    volumes:
      - ./policies:/policies
