// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/reearth/reearth-accounts/server/internal/admin/presentation"
	adminuserhandler "github.com/reearth/reearth-accounts/server/internal/admin/presentation/handler/adminuser"
	"github.com/reearth/reearth-accounts/server/internal/admin/presentation/handler/auth"
	"github.com/reearth/reearth-accounts/server/internal/admin/presentation/handler/user"
	workspacehandler "github.com/reearth/reearth-accounts/server/internal/admin/presentation/handler/workspace"
	"github.com/reearth/reearth-accounts/server/internal/admin/presentation/middleware"
	"github.com/reearth/reearth-accounts/server/internal/admin/usecase/adminuseruc"
	"github.com/reearth/reearth-accounts/server/internal/admin/usecase/authuc"
	"github.com/reearth/reearth-accounts/server/internal/admin/usecase/authz"
	"github.com/reearth/reearth-accounts/server/internal/admin/usecase/useruc"
	"github.com/reearth/reearth-accounts/server/internal/admin/usecase/workspaceuc"
)

// Injectors from wire.go:

// InitializeEcho builds the fully-wired admin Echo server. The returned cleanup
// function tears down resources (e.g. the DB connection).
func InitializeEcho() (*Server, func(), error) {
	config := LoadConfig()
	container, cleanup, err := provideRepoContainer(config)
	if err != nil {
		return nil, nil, err
	}
	adminUserRepo := container.AdminUser
	repo := container.User
	grpcClient, err := provideCerbosClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	roleRepo := container.Role
	permittableRepo := container.Permittable
	checker := authz.NewChecker(grpcClient, roleRepo, permittableRepo)
	listUsersUseCase := useruc.NewListUsersUseCase(repo, checker)
	userHandler := user.NewHandler(listUsersUseCase)
	verifier, err := provideGoogleVerifier(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	googleSignInOptions := provideGoogleSignInOptions(config)
	googleSignInUseCase := authuc.NewGoogleSignInUseCase(adminUserRepo, verifier, googleSignInOptions)
	getMeUseCase := authuc.NewGetMeUseCase(adminUserRepo)
	manager, err := provideSessionManager(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cookieSecure := provideCookieSecure(config)
	authHandler := auth.NewHandler(googleSignInUseCase, getMeUseCase, manager, cookieSecure)
	listAdminUsersUseCase := adminuseruc.NewListAdminUsersUseCase(adminUserRepo)
	approveAdminUserUseCase := adminuseruc.NewApproveAdminUserUseCase(adminUserRepo)
	rejectAdminUserUseCase := adminuseruc.NewRejectAdminUserUseCase(adminUserRepo)
	adminUserHandler := adminuserhandler.NewHandler(listAdminUsersUseCase, approveAdminUserUseCase, rejectAdminUserUseCase)
	workspaceRepo := container.Workspace
	listWorkspacesUseCase := workspaceuc.NewListWorkspacesUseCase(workspaceRepo)
	workspaceHandler := workspacehandler.NewHandler(listWorkspacesUseCase)
	v := provideJWTProviders(config)
	middlewareFunc, err := middleware.NewAuthMiddleware(v, repo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	sessionMiddleware := middleware.NewSessionMiddleware(manager)
	requireApprovedMiddleware := middleware.NewRequireApprovedMiddleware(manager, adminUserRepo)
	presentationHandler := presentation.NewHandler(adminUserHandler, authHandler, userHandler, workspaceHandler, middlewareFunc, sessionMiddleware, requireApprovedMiddleware)
	appMiddlewares := presentation.NewAppMiddlewares()
	server := NewAppEchoServer(config, presentationHandler, appMiddlewares)
	return server, func() {
		cleanup()
	}, nil
}
