// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mockrepo/mockrepo.go -package=mockrepo -mock_names=Repo=MockWorkspaceRepos
//

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	workspace "github.com/reearth/reearth-accounts/server/pkg/workspace"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkspaceRepo is a mock of WorkspaceRepo interface.
type MockWorkspaceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceRepoMockRecorder
	isgomock struct{}
}

// MockWorkspaceRepoMockRecorder is the mock recorder for MockWorkspaceRepo.
type MockWorkspaceRepoMockRecorder struct {
	mock *MockWorkspaceRepo
}

// NewMockWorkspaceRepo creates a new mock instance.
func NewMockWorkspaceRepo(ctrl *gomock.Controller) *MockWorkspaceRepo {
	mock := &MockWorkspaceRepo{ctrl: ctrl}
	mock.recorder = &MockWorkspaceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceRepo) EXPECT() *MockWorkspaceRepoMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockWorkspaceRepo) AddUser(ctx context.Context, id, userID string, role workspace.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, id, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockWorkspaceRepoMockRecorder) AddUser(ctx, id, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockWorkspaceRepo)(nil).AddUser), ctx, id, userID, role)
}

// Create mocks base method.
func (m *MockWorkspaceRepo) Create(ctx context.Context, name, alias, description string) (*workspace.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, alias, description)
	ret0, _ := ret[0].(*workspace.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWorkspaceRepoMockRecorder) Create(ctx, name, alias, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkspaceRepo)(nil).Create), ctx, name, alias, description)
}

// Delete mocks base method.
func (m *MockWorkspaceRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkspaceRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkspaceRepo)(nil).Delete), ctx, id)
}

// FindByAlias mocks base method.
func (m *MockWorkspaceRepo) FindByAlias(ctx context.Context, alias string) (*workspace.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAlias", ctx, alias)
	ret0, _ := ret[0].(*workspace.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAlias indicates an expected call of FindByAlias.
func (mr *MockWorkspaceRepoMockRecorder) FindByAlias(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAlias", reflect.TypeOf((*MockWorkspaceRepo)(nil).FindByAlias), ctx, alias)
}

// FindByID mocks base method.
func (m *MockWorkspaceRepo) FindByID(ctx context.Context, id string) (*workspace.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*workspace.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockWorkspaceRepoMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockWorkspaceRepo)(nil).FindByID), ctx, id)
}

// FindByUser mocks base method.
func (m *MockWorkspaceRepo) FindByUser(ctx context.Context, userID string) (workspace.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUser", ctx, userID)
	ret0, _ := ret[0].(workspace.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUser indicates an expected call of FindByUser.
func (mr *MockWorkspaceRepoMockRecorder) FindByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUser", reflect.TypeOf((*MockWorkspaceRepo)(nil).FindByUser), ctx, userID)
}

// FindByUserWithPagination mocks base method.
func (m *MockWorkspaceRepo) FindByUserWithPagination(ctx context.Context, userID string, page, size int64) (workspace.List, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserWithPagination", ctx, userID, page, size)
	ret0, _ := ret[0].(workspace.List)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserWithPagination indicates an expected call of FindByUserWithPagination.
func (mr *MockWorkspaceRepoMockRecorder) FindByUserWithPagination(ctx, userID, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserWithPagination", reflect.TypeOf((*MockWorkspaceRepo)(nil).FindByUserWithPagination), ctx, userID, page, size)
}

// RemoveUser mocks base method.
func (m *MockWorkspaceRepo) RemoveUser(ctx context.Context, workspaceID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUser", ctx, workspaceID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUser indicates an expected call of RemoveUser.
func (mr *MockWorkspaceRepoMockRecorder) RemoveUser(ctx, workspaceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUser", reflect.TypeOf((*MockWorkspaceRepo)(nil).RemoveUser), ctx, workspaceID, userID)
}

// TransferOwnership mocks base method.
func (m *MockWorkspaceRepo) TransferOwnership(ctx context.Context, workspaceID, newOwnerID string) (*workspace.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferOwnership", ctx, workspaceID, newOwnerID)
	ret0, _ := ret[0].(*workspace.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferOwnership indicates an expected call of TransferOwnership.
func (mr *MockWorkspaceRepoMockRecorder) TransferOwnership(ctx, workspaceID, newOwnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferOwnership", reflect.TypeOf((*MockWorkspaceRepo)(nil).TransferOwnership), ctx, workspaceID, newOwnerID)
}

// Update mocks base method.
func (m *MockWorkspaceRepo) Update(ctx context.Context, id, alias, name, email, website, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, alias, name, email, website, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWorkspaceRepoMockRecorder) Update(ctx, id, alias, name, email, website, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkspaceRepo)(nil).Update), ctx, id, alias, name, email, website, description)
}
