// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mockrepo/mockrepo.go -package=mockrepo -mock_names=Repo=MockWorkspaceRepos
//

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	workspace "github.com/reearth/reearth-accounts/server/pkg/gqlclient/workspace"
	workspace0 "github.com/reearth/reearth-accounts/server/pkg/workspace"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkspaceRepo is a mock of WorkspaceRepo interface.
type MockWorkspaceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceRepoMockRecorder
	isgomock struct{}
}

// MockWorkspaceRepoMockRecorder is the mock recorder for MockWorkspaceRepo.
type MockWorkspaceRepoMockRecorder struct {
	mock *MockWorkspaceRepo
}

// NewMockWorkspaceRepo creates a new mock instance.
func NewMockWorkspaceRepo(ctrl *gomock.Controller) *MockWorkspaceRepo {
	mock := &MockWorkspaceRepo{ctrl: ctrl}
	mock.recorder = &MockWorkspaceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceRepo) EXPECT() *MockWorkspaceRepoMockRecorder {
	return m.recorder
}

// AddUsersToWorkspace mocks base method.
func (m *MockWorkspaceRepo) AddUsersToWorkspace(ctx context.Context, input workspace.AddUsersToWorkspaceInput) (*workspace0.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUsersToWorkspace", ctx, input)
	ret0, _ := ret[0].(*workspace0.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUsersToWorkspace indicates an expected call of AddUsersToWorkspace.
func (mr *MockWorkspaceRepoMockRecorder) AddUsersToWorkspace(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUsersToWorkspace", reflect.TypeOf((*MockWorkspaceRepo)(nil).AddUsersToWorkspace), ctx, input)
}

// CreateWorkspace mocks base method.
func (m *MockWorkspaceRepo) CreateWorkspace(ctx context.Context, input workspace.CreateWorkspaceInput) (*workspace0.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspace", ctx, input)
	ret0, _ := ret[0].(*workspace0.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspace indicates an expected call of CreateWorkspace.
func (mr *MockWorkspaceRepoMockRecorder) CreateWorkspace(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspace", reflect.TypeOf((*MockWorkspaceRepo)(nil).CreateWorkspace), ctx, input)
}

// DeleteWorkspace mocks base method.
func (m *MockWorkspaceRepo) DeleteWorkspace(ctx context.Context, workspaceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspace", ctx, workspaceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspace indicates an expected call of DeleteWorkspace.
func (mr *MockWorkspaceRepoMockRecorder) DeleteWorkspace(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspace", reflect.TypeOf((*MockWorkspaceRepo)(nil).DeleteWorkspace), ctx, workspaceID)
}

// FindByAlias mocks base method.
func (m *MockWorkspaceRepo) FindByAlias(ctx context.Context, alias string) (*workspace0.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAlias", ctx, alias)
	ret0, _ := ret[0].(*workspace0.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAlias indicates an expected call of FindByAlias.
func (mr *MockWorkspaceRepoMockRecorder) FindByAlias(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAlias", reflect.TypeOf((*MockWorkspaceRepo)(nil).FindByAlias), ctx, alias)
}

// FindByID mocks base method.
func (m *MockWorkspaceRepo) FindByID(ctx context.Context, id string) (*workspace0.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*workspace0.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockWorkspaceRepoMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockWorkspaceRepo)(nil).FindByID), ctx, id)
}

// FindByIDs mocks base method.
func (m *MockWorkspaceRepo) FindByIDs(ctx context.Context, ids []string) (workspace0.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, ids)
	ret0, _ := ret[0].(workspace0.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockWorkspaceRepoMockRecorder) FindByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockWorkspaceRepo)(nil).FindByIDs), ctx, ids)
}

// FindByUser mocks base method.
func (m *MockWorkspaceRepo) FindByUser(ctx context.Context, userID string) (workspace0.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUser", ctx, userID)
	ret0, _ := ret[0].(workspace0.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUser indicates an expected call of FindByUser.
func (mr *MockWorkspaceRepoMockRecorder) FindByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUser", reflect.TypeOf((*MockWorkspaceRepo)(nil).FindByUser), ctx, userID)
}

// FindByUserWithPagination mocks base method.
func (m *MockWorkspaceRepo) FindByUserWithPagination(ctx context.Context, userID string, page, size int64) (workspace0.List, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserWithPagination", ctx, userID, page, size)
	ret0, _ := ret[0].(workspace0.List)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserWithPagination indicates an expected call of FindByUserWithPagination.
func (mr *MockWorkspaceRepoMockRecorder) FindByUserWithPagination(ctx, userID, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserWithPagination", reflect.TypeOf((*MockWorkspaceRepo)(nil).FindByUserWithPagination), ctx, userID, page, size)
}

// RemoveUserFromWorkspace mocks base method.
func (m *MockWorkspaceRepo) RemoveUserFromWorkspace(ctx context.Context, workspaceID, userID string) (*workspace0.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromWorkspace", ctx, workspaceID, userID)
	ret0, _ := ret[0].(*workspace0.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveUserFromWorkspace indicates an expected call of RemoveUserFromWorkspace.
func (mr *MockWorkspaceRepoMockRecorder) RemoveUserFromWorkspace(ctx, workspaceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromWorkspace", reflect.TypeOf((*MockWorkspaceRepo)(nil).RemoveUserFromWorkspace), ctx, workspaceID, userID)
}

// TransferOwnership mocks base method.
func (m *MockWorkspaceRepo) TransferOwnership(ctx context.Context, workspaceID, newOwnerID string) (*workspace0.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferOwnership", ctx, workspaceID, newOwnerID)
	ret0, _ := ret[0].(*workspace0.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferOwnership indicates an expected call of TransferOwnership.
func (mr *MockWorkspaceRepoMockRecorder) TransferOwnership(ctx, workspaceID, newOwnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferOwnership", reflect.TypeOf((*MockWorkspaceRepo)(nil).TransferOwnership), ctx, workspaceID, newOwnerID)
}

// UpdateUserOfWorkspace mocks base method.
func (m *MockWorkspaceRepo) UpdateUserOfWorkspace(ctx context.Context, input workspace.UpdateUserOfWorkspaceInput) (*workspace0.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserOfWorkspace", ctx, input)
	ret0, _ := ret[0].(*workspace0.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserOfWorkspace indicates an expected call of UpdateUserOfWorkspace.
func (mr *MockWorkspaceRepoMockRecorder) UpdateUserOfWorkspace(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserOfWorkspace", reflect.TypeOf((*MockWorkspaceRepo)(nil).UpdateUserOfWorkspace), ctx, input)
}

// UpdateWorkspace mocks base method.
func (m *MockWorkspaceRepo) UpdateWorkspace(ctx context.Context, input workspace.UpdateWorkspaceInput) (*workspace0.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkspace", ctx, input)
	ret0, _ := ret[0].(*workspace0.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkspace indicates an expected call of UpdateWorkspace.
func (mr *MockWorkspaceRepoMockRecorder) UpdateWorkspace(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkspace", reflect.TypeOf((*MockWorkspaceRepo)(nil).UpdateWorkspace), ctx, input)
}
