// Code generated by MockGen. DO NOT EDIT.
// Source: ./repo.go
//
// Generated by this command:
//
//	mockgen -source=./repo.go -destination=./mock_workspace.go -package workspace
//

// Package workspace is a generated GoMock package.
package workspace

import (
	context "context"
	reflect "reflect"

	user "github.com/reearth/reearth-accounts/server/pkg/user"
	usecasex "github.com/reearth/reearthx/usecasex"
	gomock "go.uber.org/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
	isgomock struct{}
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepo) Create(arg0 context.Context, arg1 *Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepoMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepo)(nil).Create), arg0, arg1)
}

// Filtered mocks base method.
func (m *MockRepo) Filtered(arg0 WorkspaceFilter) Repo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filtered", arg0)
	ret0, _ := ret[0].(Repo)
	return ret0
}

// Filtered indicates an expected call of Filtered.
func (mr *MockRepoMockRecorder) Filtered(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filtered", reflect.TypeOf((*MockRepo)(nil).Filtered), arg0)
}

// FindByAlias mocks base method.
func (m *MockRepo) FindByAlias(ctx context.Context, alias string) (*Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAlias", ctx, alias)
	ret0, _ := ret[0].(*Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAlias indicates an expected call of FindByAlias.
func (mr *MockRepoMockRecorder) FindByAlias(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAlias", reflect.TypeOf((*MockRepo)(nil).FindByAlias), ctx, alias)
}

// FindByAliases mocks base method.
func (m *MockRepo) FindByAliases(ctx context.Context, aliases []string) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAliases", ctx, aliases)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAliases indicates an expected call of FindByAliases.
func (mr *MockRepoMockRecorder) FindByAliases(ctx, aliases any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAliases", reflect.TypeOf((*MockRepo)(nil).FindByAliases), ctx, aliases)
}

// FindByID mocks base method.
func (m *MockRepo) FindByID(arg0 context.Context, arg1 ID) (*Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepoMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepo)(nil).FindByID), arg0, arg1)
}

// FindByIDs mocks base method.
func (m *MockRepo) FindByIDs(arg0 context.Context, arg1 IDList) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", arg0, arg1)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockRepoMockRecorder) FindByIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockRepo)(nil).FindByIDs), arg0, arg1)
}

// FindByIntegration mocks base method.
func (m *MockRepo) FindByIntegration(arg0 context.Context, arg1 IntegrationID) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIntegration", arg0, arg1)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIntegration indicates an expected call of FindByIntegration.
func (mr *MockRepoMockRecorder) FindByIntegration(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIntegration", reflect.TypeOf((*MockRepo)(nil).FindByIntegration), arg0, arg1)
}

// FindByIntegrations mocks base method.
func (m *MockRepo) FindByIntegrations(arg0 context.Context, arg1 IntegrationIDList) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIntegrations", arg0, arg1)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIntegrations indicates an expected call of FindByIntegrations.
func (mr *MockRepoMockRecorder) FindByIntegrations(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIntegrations", reflect.TypeOf((*MockRepo)(nil).FindByIntegrations), arg0, arg1)
}

// FindByName mocks base method.
func (m *MockRepo) FindByName(arg0 context.Context, arg1 string) (*Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", arg0, arg1)
	ret0, _ := ret[0].(*Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockRepoMockRecorder) FindByName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockRepo)(nil).FindByName), arg0, arg1)
}

// FindByUser mocks base method.
func (m *MockRepo) FindByUser(arg0 context.Context, arg1 user.ID) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUser", arg0, arg1)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUser indicates an expected call of FindByUser.
func (mr *MockRepoMockRecorder) FindByUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUser", reflect.TypeOf((*MockRepo)(nil).FindByUser), arg0, arg1)
}

// FindByUserWithPagination mocks base method.
func (m *MockRepo) FindByUserWithPagination(ctx context.Context, id user.ID, pagination *usecasex.Pagination) (List, *usecasex.PageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserWithPagination", ctx, id, pagination)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(*usecasex.PageInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserWithPagination indicates an expected call of FindByUserWithPagination.
func (mr *MockRepoMockRecorder) FindByUserWithPagination(ctx, id, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserWithPagination", reflect.TypeOf((*MockRepo)(nil).FindByUserWithPagination), ctx, id, pagination)
}

// Remove mocks base method.
func (m *MockRepo) Remove(arg0 context.Context, arg1 ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRepoMockRecorder) Remove(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRepo)(nil).Remove), arg0, arg1)
}

// RemoveAll mocks base method.
func (m *MockRepo) RemoveAll(arg0 context.Context, arg1 IDList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockRepoMockRecorder) RemoveAll(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockRepo)(nil).RemoveAll), arg0, arg1)
}

// Save mocks base method.
func (m *MockRepo) Save(arg0 context.Context, arg1 *Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepoMockRecorder) Save(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepo)(nil).Save), arg0, arg1)
}

// SaveAll mocks base method.
func (m *MockRepo) SaveAll(arg0 context.Context, arg1 List) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAll", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAll indicates an expected call of SaveAll.
func (mr *MockRepoMockRecorder) SaveAll(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAll", reflect.TypeOf((*MockRepo)(nil).SaveAll), arg0, arg1)
}
