// Code generated by migrategen, DO NOT EDIT.

package migration

import "github.com/reearth/reearthx/usecasex/migration"

// To add a new migration, run go run ./tools/cmd/migrategen migration_name

// WARNING:
// If the migration takes too long, the deployment may fail in a serverless environment.
// Set the batch size to as large a value as possible without using up the RAM of the deployment destination.
var migrations = migration.Migrations[DBClient]{
	250617171055: AddMetadataWorkspace,
	250617171056: AddMetadataUser,
	250617171057: AddMetadataWorkspaceV2,
	250617171058: AddMetadataUserV2,
	250724212700: AddMetadataUserV3,
	250725020842: ConvertNonValidUserAlias,
	250725020843: ConvertNonValidWorkspaceAlias,
	250919170404: ConvertInvalidUserAlias,
	250919170408: ConvertInvalidUserWorkspaceAlias,
	251106072200: ReplaceEmailFormattedNames,
	251107102200: SyncPersonalWorkspaceAlias,
	251114101525: SyncUserNameToWorkspace,
	251119144500: AddWorkspaceMembersHash,
	251120200000: GenerateMissingWorkspaceAliases,
	251209170001: AddRoles,
	251209170002: MoveWorkspaceMembersRoleToPermittable,
	// TODO:
	// it doesn't have enough test
	// so skip it for now
	// 251224140400: ApplyCollectionSchemas1,
	260108175500: FixPermittableRoleIDs,
	260109104153: FixPermittableWorkspaceRoles,
	// TODO: need to verify MongoDB permission to use `listCollections` to apply the migrations below
	// 260114000000: ApplyUserUpdatedAtSchema,
	// 260114000001: ApplyWorkspaceUpdatedAtSchema,
	260122110000: AddCaseInsensitiveWorkspaceAliasIndex,
	260122110001: ReplaceWorkspaceAliasMembersIndex,
	260122110002: GenerateMissingUserAliases,
	260122110003: AddCaseInsensitiveUserAliasIndex,
	260122110004: AddCaseInsensitiveUserEmailIndex,
	260122110005: AddCaseInsensitiveUserWorkspaceIndex,
}
