// Code generated by MockGen. DO NOT EDIT.
// Source: ./repo.go
//
// Generated by this command:
//
//	mockgen -source=./repo.go -destination=./mock_permittable.go -package permittable
//

// Package permittable is a generated GoMock package.
package permittable

import (
	context "context"
	reflect "reflect"

	id "github.com/reearth/reearth-accounts/server/pkg/id"
	user "github.com/reearth/reearth-accounts/server/pkg/user"
	gomock "go.uber.org/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
	isgomock struct{}
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// FindByRoleID mocks base method.
func (m *MockRepo) FindByRoleID(arg0 context.Context, arg1 id.RoleID) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRoleID", arg0, arg1)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRoleID indicates an expected call of FindByRoleID.
func (mr *MockRepoMockRecorder) FindByRoleID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRoleID", reflect.TypeOf((*MockRepo)(nil).FindByRoleID), arg0, arg1)
}

// FindByUserID mocks base method.
func (m *MockRepo) FindByUserID(arg0 context.Context, arg1 user.ID) (*Permittable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", arg0, arg1)
	ret0, _ := ret[0].(*Permittable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockRepoMockRecorder) FindByUserID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockRepo)(nil).FindByUserID), arg0, arg1)
}

// FindByUserIDs mocks base method.
func (m *MockRepo) FindByUserIDs(arg0 context.Context, arg1 user.IDList) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDs", arg0, arg1)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDs indicates an expected call of FindByUserIDs.
func (mr *MockRepoMockRecorder) FindByUserIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDs", reflect.TypeOf((*MockRepo)(nil).FindByUserIDs), arg0, arg1)
}

// Save mocks base method.
func (m *MockRepo) Save(arg0 context.Context, arg1 Permittable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepoMockRecorder) Save(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepo)(nil).Save), arg0, arg1)
}
