// Code generated by MockGen. DO NOT EDIT.
// Source: ./permittable.go
//
// Generated by this command:
//
//	mockgen -source=./permittable.go -destination=./mock_permittable.go -package permittable
//

// Package permittable is a generated GoMock package.
package permittable
