// Code generated by MockGen. DO NOT EDIT.
// Source: ./user.go
//
// Generated by this command:
//
//	mockgen -source=./user.go -destination=./mock_user.go -package user
//

// Package user is a generated GoMock package.
package user
