// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/user/repo.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/user/repo.go -destination=./pkg/user/mock_user.go -package user
//

// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"

	usecasex "github.com/reearth/reearthx/usecasex"
	gomock "go.uber.org/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
	isgomock struct{}
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepo) Create(arg0 context.Context, arg1 *User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepoMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepo)(nil).Create), arg0, arg1)
}

// FindAll mocks base method.
func (m *MockRepo) FindAll(arg0 context.Context) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRepoMockRecorder) FindAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRepo)(nil).FindAll), arg0)
}

// FindAllWithPagination mocks base method.
func (m *MockRepo) FindAllWithPagination(ctx context.Context, keyword *string, pagination *usecasex.Pagination) (List, *usecasex.PageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithPagination", ctx, keyword, pagination)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(*usecasex.PageInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllWithPagination indicates an expected call of FindAllWithPagination.
func (mr *MockRepoMockRecorder) FindAllWithPagination(ctx, keyword, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithPagination", reflect.TypeOf((*MockRepo)(nil).FindAllWithPagination), ctx, keyword, pagination)
}

// FindByAlias mocks base method.
func (m *MockRepo) FindByAlias(arg0 context.Context, arg1 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAlias", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAlias indicates an expected call of FindByAlias.
func (mr *MockRepoMockRecorder) FindByAlias(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAlias", reflect.TypeOf((*MockRepo)(nil).FindByAlias), arg0, arg1)
}

// FindByEmail mocks base method.
func (m *MockRepo) FindByEmail(arg0 context.Context, arg1 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockRepoMockRecorder) FindByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockRepo)(nil).FindByEmail), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockRepo) FindByID(arg0 context.Context, arg1 ID) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepoMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepo)(nil).FindByID), arg0, arg1)
}

// FindByIDs mocks base method.
func (m *MockRepo) FindByIDs(arg0 context.Context, arg1 IDList) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", arg0, arg1)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockRepoMockRecorder) FindByIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockRepo)(nil).FindByIDs), arg0, arg1)
}

// FindByIDsWithPagination mocks base method.
func (m *MockRepo) FindByIDsWithPagination(arg0 context.Context, arg1 IDList, arg2 *string, arg3 *usecasex.Pagination) (List, *usecasex.PageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDsWithPagination", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(*usecasex.PageInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByIDsWithPagination indicates an expected call of FindByIDsWithPagination.
func (mr *MockRepoMockRecorder) FindByIDsWithPagination(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDsWithPagination", reflect.TypeOf((*MockRepo)(nil).FindByIDsWithPagination), arg0, arg1, arg2, arg3)
}

// FindByName mocks base method.
func (m *MockRepo) FindByName(arg0 context.Context, arg1 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockRepoMockRecorder) FindByName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockRepo)(nil).FindByName), arg0, arg1)
}

// FindByNameOrAlias mocks base method.
func (m *MockRepo) FindByNameOrAlias(arg0 context.Context, arg1 string) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNameOrAlias", arg0, arg1)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNameOrAlias indicates an expected call of FindByNameOrAlias.
func (mr *MockRepoMockRecorder) FindByNameOrAlias(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNameOrAlias", reflect.TypeOf((*MockRepo)(nil).FindByNameOrAlias), arg0, arg1)
}

// FindByNameOrEmail mocks base method.
func (m *MockRepo) FindByNameOrEmail(arg0 context.Context, arg1 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNameOrEmail", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNameOrEmail indicates an expected call of FindByNameOrEmail.
func (mr *MockRepoMockRecorder) FindByNameOrEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNameOrEmail", reflect.TypeOf((*MockRepo)(nil).FindByNameOrEmail), arg0, arg1)
}

// FindByPasswordResetRequest mocks base method.
func (m *MockRepo) FindByPasswordResetRequest(arg0 context.Context, arg1 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPasswordResetRequest", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPasswordResetRequest indicates an expected call of FindByPasswordResetRequest.
func (mr *MockRepoMockRecorder) FindByPasswordResetRequest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPasswordResetRequest", reflect.TypeOf((*MockRepo)(nil).FindByPasswordResetRequest), arg0, arg1)
}

// FindBySub mocks base method.
func (m *MockRepo) FindBySub(arg0 context.Context, arg1 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySub", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySub indicates an expected call of FindBySub.
func (mr *MockRepoMockRecorder) FindBySub(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySub", reflect.TypeOf((*MockRepo)(nil).FindBySub), arg0, arg1)
}

// FindBySubOrCreate mocks base method.
func (m *MockRepo) FindBySubOrCreate(arg0 context.Context, arg1 *User, arg2 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySubOrCreate", arg0, arg1, arg2)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySubOrCreate indicates an expected call of FindBySubOrCreate.
func (mr *MockRepoMockRecorder) FindBySubOrCreate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySubOrCreate", reflect.TypeOf((*MockRepo)(nil).FindBySubOrCreate), arg0, arg1, arg2)
}

// FindByVerification mocks base method.
func (m *MockRepo) FindByVerification(arg0 context.Context, arg1 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByVerification", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByVerification indicates an expected call of FindByVerification.
func (mr *MockRepoMockRecorder) FindByVerification(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByVerification", reflect.TypeOf((*MockRepo)(nil).FindByVerification), arg0, arg1)
}

// Remove mocks base method.
func (m *MockRepo) Remove(arg0 context.Context, arg1 ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRepoMockRecorder) Remove(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRepo)(nil).Remove), arg0, arg1)
}

// Save mocks base method.
func (m *MockRepo) Save(arg0 context.Context, arg1 *User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepoMockRecorder) Save(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepo)(nil).Save), arg0, arg1)
}

// SearchByKeyword mocks base method.
func (m *MockRepo) SearchByKeyword(arg0 context.Context, arg1 string) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByKeyword", arg0, arg1)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByKeyword indicates an expected call of SearchByKeyword.
func (mr *MockRepoMockRecorder) SearchByKeyword(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByKeyword", reflect.TypeOf((*MockRepo)(nil).SearchByKeyword), arg0, arg1)
}

// MockQuery is a mock of Query interface.
type MockQuery struct {
	ctrl     *gomock.Controller
	recorder *MockQueryMockRecorder
	isgomock struct{}
}

// MockQueryMockRecorder is the mock recorder for MockQuery.
type MockQueryMockRecorder struct {
	mock *MockQuery
}

// NewMockQuery creates a new mock instance.
func NewMockQuery(ctrl *gomock.Controller) *MockQuery {
	mock := &MockQuery{ctrl: ctrl}
	mock.recorder = &MockQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuery) EXPECT() *MockQueryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockQuery) FindAll(arg0 context.Context) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockQueryMockRecorder) FindAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockQuery)(nil).FindAll), arg0)
}

// FindAllWithPagination mocks base method.
func (m *MockQuery) FindAllWithPagination(ctx context.Context, keyword *string, pagination *usecasex.Pagination) (List, *usecasex.PageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithPagination", ctx, keyword, pagination)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(*usecasex.PageInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllWithPagination indicates an expected call of FindAllWithPagination.
func (mr *MockQueryMockRecorder) FindAllWithPagination(ctx, keyword, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithPagination", reflect.TypeOf((*MockQuery)(nil).FindAllWithPagination), ctx, keyword, pagination)
}

// FindByAlias mocks base method.
func (m *MockQuery) FindByAlias(arg0 context.Context, arg1 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAlias", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAlias indicates an expected call of FindByAlias.
func (mr *MockQueryMockRecorder) FindByAlias(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAlias", reflect.TypeOf((*MockQuery)(nil).FindByAlias), arg0, arg1)
}

// FindByEmail mocks base method.
func (m *MockQuery) FindByEmail(arg0 context.Context, arg1 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockQueryMockRecorder) FindByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockQuery)(nil).FindByEmail), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockQuery) FindByID(arg0 context.Context, arg1 ID) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockQueryMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockQuery)(nil).FindByID), arg0, arg1)
}

// FindByIDs mocks base method.
func (m *MockQuery) FindByIDs(arg0 context.Context, arg1 IDList) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", arg0, arg1)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockQueryMockRecorder) FindByIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockQuery)(nil).FindByIDs), arg0, arg1)
}

// FindByIDsWithPagination mocks base method.
func (m *MockQuery) FindByIDsWithPagination(arg0 context.Context, arg1 IDList, arg2 *string, arg3 *usecasex.Pagination) (List, *usecasex.PageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDsWithPagination", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(*usecasex.PageInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByIDsWithPagination indicates an expected call of FindByIDsWithPagination.
func (mr *MockQueryMockRecorder) FindByIDsWithPagination(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDsWithPagination", reflect.TypeOf((*MockQuery)(nil).FindByIDsWithPagination), arg0, arg1, arg2, arg3)
}

// FindByName mocks base method.
func (m *MockQuery) FindByName(arg0 context.Context, arg1 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockQueryMockRecorder) FindByName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockQuery)(nil).FindByName), arg0, arg1)
}

// FindByNameOrAlias mocks base method.
func (m *MockQuery) FindByNameOrAlias(arg0 context.Context, arg1 string) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNameOrAlias", arg0, arg1)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNameOrAlias indicates an expected call of FindByNameOrAlias.
func (mr *MockQueryMockRecorder) FindByNameOrAlias(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNameOrAlias", reflect.TypeOf((*MockQuery)(nil).FindByNameOrAlias), arg0, arg1)
}

// FindByNameOrEmail mocks base method.
func (m *MockQuery) FindByNameOrEmail(arg0 context.Context, arg1 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNameOrEmail", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNameOrEmail indicates an expected call of FindByNameOrEmail.
func (mr *MockQueryMockRecorder) FindByNameOrEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNameOrEmail", reflect.TypeOf((*MockQuery)(nil).FindByNameOrEmail), arg0, arg1)
}

// FindBySub mocks base method.
func (m *MockQuery) FindBySub(arg0 context.Context, arg1 string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySub", arg0, arg1)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySub indicates an expected call of FindBySub.
func (mr *MockQueryMockRecorder) FindBySub(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySub", reflect.TypeOf((*MockQuery)(nil).FindBySub), arg0, arg1)
}

// SearchByKeyword mocks base method.
func (m *MockQuery) SearchByKeyword(arg0 context.Context, arg1 string) (List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByKeyword", arg0, arg1)
	ret0, _ := ret[0].(List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByKeyword indicates an expected call of SearchByKeyword.
func (mr *MockQueryMockRecorder) SearchByKeyword(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByKeyword", reflect.TypeOf((*MockQuery)(nil).SearchByKeyword), arg0, arg1)
}
