// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/reearth/reearth-accounts/server/internal/reearth-accounts-admin/presentation"
	"github.com/reearth/reearth-accounts/server/internal/reearth-accounts-admin/presentation/handler/user"
	"github.com/reearth/reearth-accounts/server/internal/reearth-accounts-admin/presentation/middleware"
	"github.com/reearth/reearth-accounts/server/internal/reearth-accounts-admin/usecase/authz"
	"github.com/reearth/reearth-accounts/server/internal/reearth-accounts-admin/usecase/useruc"
)

// Injectors from wire.go:

// InitializeEcho builds the fully-wired admin Echo server. The returned cleanup
// function tears down resources (e.g. the DB connection).
func InitializeEcho() (*Server, func(), error) {
	config := LoadConfig()
	container, cleanup, err := provideRepoContainer(config)
	if err != nil {
		return nil, nil, err
	}
	repo := container.User
	grpcClient, err := provideCerbosClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	roleRepo := container.Role
	permittableRepo := container.Permittable
	checker := authz.NewChecker(grpcClient, roleRepo, permittableRepo)
	listUsersUseCase := useruc.NewListUsersUseCase(repo, checker)
	handler := user.NewHandler(listUsersUseCase)
	v := provideJWTProviders(config)
	middlewareFunc, err := middleware.NewAuthMiddleware(v, repo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	presentationHandler := presentation.NewHandler(handler, middlewareFunc)
	appMiddlewares := presentation.NewAppMiddlewares()
	server := NewAppEchoServer(config, presentationHandler, appMiddlewares)
	return server, func() {
		cleanup()
	}, nil
}
