// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mockrepo/mockrepo.go -package=mockrepo -mock_names=Repo=MockUserRepos
//

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	user "github.com/reearth/reearth-accounts/server/pkg/gqlclient/user"
	user0 "github.com/reearth/reearth-accounts/server/pkg/user"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepos is a mock of Repo interface.
type MockUserRepos struct {
	ctrl     *gomock.Controller
	recorder *MockUserReposMockRecorder
	isgomock struct{}
}

// MockUserReposMockRecorder is the mock recorder for MockUserRepos.
type MockUserReposMockRecorder struct {
	mock *MockUserRepos
}

// NewMockUserRepos creates a new mock instance.
func NewMockUserRepos(ctrl *gomock.Controller) *MockUserRepos {
	mock := &MockUserRepos{ctrl: ctrl}
	mock.recorder = &MockUserReposMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepos) EXPECT() *MockUserReposMockRecorder {
	return m.recorder
}

// CreateVerification mocks base method.
func (m *MockUserRepos) CreateVerification(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerification", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVerification indicates an expected call of CreateVerification.
func (mr *MockUserReposMockRecorder) CreateVerification(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerification", reflect.TypeOf((*MockUserRepos)(nil).CreateVerification), ctx, email)
}

// DeleteMe mocks base method.
func (m *MockUserRepos) DeleteMe(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMe", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMe indicates an expected call of DeleteMe.
func (mr *MockUserReposMockRecorder) DeleteMe(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMe", reflect.TypeOf((*MockUserRepos)(nil).DeleteMe), ctx, userID)
}

// FindByAlias mocks base method.
func (m *MockUserRepos) FindByAlias(ctx context.Context, name string) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAlias", ctx, name)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAlias indicates an expected call of FindByAlias.
func (mr *MockUserReposMockRecorder) FindByAlias(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAlias", reflect.TypeOf((*MockUserRepos)(nil).FindByAlias), ctx, name)
}

// FindByID mocks base method.
func (m *MockUserRepos) FindByID(ctx context.Context, id string) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserReposMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepos)(nil).FindByID), ctx, id)
}

// FindMe mocks base method.
func (m *MockUserRepos) FindMe(ctx context.Context) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMe", ctx)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMe indicates an expected call of FindMe.
func (mr *MockUserReposMockRecorder) FindMe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMe", reflect.TypeOf((*MockUserRepos)(nil).FindMe), ctx)
}

// RemoveMyAuth mocks base method.
func (m *MockUserRepos) RemoveMyAuth(ctx context.Context, auth string) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMyAuth", ctx, auth)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveMyAuth indicates an expected call of RemoveMyAuth.
func (mr *MockUserReposMockRecorder) RemoveMyAuth(ctx, auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMyAuth", reflect.TypeOf((*MockUserRepos)(nil).RemoveMyAuth), ctx, auth)
}

// Signup mocks base method.
func (m *MockUserRepos) Signup(ctx context.Context, userID, name, email, password, secret, workspaceID string, mockAuth bool) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", ctx, userID, name, email, password, secret, workspaceID, mockAuth)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signup indicates an expected call of Signup.
func (mr *MockUserReposMockRecorder) Signup(ctx, userID, name, email, password, secret, workspaceID, mockAuth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockUserRepos)(nil).Signup), ctx, userID, name, email, password, secret, workspaceID, mockAuth)
}

// SignupOIDC mocks base method.
func (m *MockUserRepos) SignupOIDC(ctx context.Context, name, email, sub, secret string) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignupOIDC", ctx, name, email, sub, secret)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignupOIDC indicates an expected call of SignupOIDC.
func (mr *MockUserReposMockRecorder) SignupOIDC(ctx, name, email, sub, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignupOIDC", reflect.TypeOf((*MockUserRepos)(nil).SignupOIDC), ctx, name, email, sub, secret)
}

// Update mocks base method.
func (m *MockUserRepos) Update(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserReposMockRecorder) Update(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepos)(nil).Update), ctx, name)
}

// UpdateMe mocks base method.
func (m *MockUserRepos) UpdateMe(ctx context.Context, input user.UpdateMeInput) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMe", ctx, input)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMe indicates an expected call of UpdateMe.
func (mr *MockUserReposMockRecorder) UpdateMe(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMe", reflect.TypeOf((*MockUserRepos)(nil).UpdateMe), ctx, input)
}
