// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mockrepo/mockrepo.go -package=mockrepo -mock_names=Repo=MockRepo
//

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	user "github.com/reearth/reearth-accounts/server/pkg/gqlclient/user"
	user0 "github.com/reearth/reearth-accounts/server/pkg/user"
	gomock "go.uber.org/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
	isgomock struct{}
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// CreateVerification mocks base method.
func (m *MockRepo) CreateVerification(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerification", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVerification indicates an expected call of CreateVerification.
func (mr *MockRepoMockRecorder) CreateVerification(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerification", reflect.TypeOf((*MockRepo)(nil).CreateVerification), ctx, email)
}

// DeleteMe mocks base method.
func (m *MockRepo) DeleteMe(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMe", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMe indicates an expected call of DeleteMe.
func (mr *MockRepoMockRecorder) DeleteMe(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMe", reflect.TypeOf((*MockRepo)(nil).DeleteMe), ctx, userID)
}

// FindByAlias mocks base method.
func (m *MockRepo) FindByAlias(ctx context.Context, alias string) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAlias", ctx, alias)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAlias indicates an expected call of FindByAlias.
func (mr *MockRepoMockRecorder) FindByAlias(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAlias", reflect.TypeOf((*MockRepo)(nil).FindByAlias), ctx, alias)
}

// FindByID mocks base method.
func (m *MockRepo) FindByID(ctx context.Context, id string) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepoMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepo)(nil).FindByID), ctx, id)
}

// FindByIDs mocks base method.
func (m *MockRepo) FindByIDs(ctx context.Context, ids []string) ([]*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, ids)
	ret0, _ := ret[0].([]*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockRepoMockRecorder) FindByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockRepo)(nil).FindByIDs), ctx, ids)
}

// FindByNameOrEmail mocks base method.
func (m *MockRepo) FindByNameOrEmail(ctx context.Context, nameOrEmail string) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNameOrEmail", ctx, nameOrEmail)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNameOrEmail indicates an expected call of FindByNameOrEmail.
func (mr *MockRepoMockRecorder) FindByNameOrEmail(ctx, nameOrEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNameOrEmail", reflect.TypeOf((*MockRepo)(nil).FindByNameOrEmail), ctx, nameOrEmail)
}

// FindMe mocks base method.
func (m *MockRepo) FindMe(ctx context.Context) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMe", ctx)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMe indicates an expected call of FindMe.
func (mr *MockRepoMockRecorder) FindMe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMe", reflect.TypeOf((*MockRepo)(nil).FindMe), ctx)
}

// PasswordReset mocks base method.
func (m *MockRepo) PasswordReset(ctx context.Context, password, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordReset", ctx, password, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// PasswordReset indicates an expected call of PasswordReset.
func (mr *MockRepoMockRecorder) PasswordReset(ctx, password, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordReset", reflect.TypeOf((*MockRepo)(nil).PasswordReset), ctx, password, token)
}

// RemoveMyAuth mocks base method.
func (m *MockRepo) RemoveMyAuth(ctx context.Context, auth string) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMyAuth", ctx, auth)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveMyAuth indicates an expected call of RemoveMyAuth.
func (mr *MockRepoMockRecorder) RemoveMyAuth(ctx, auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMyAuth", reflect.TypeOf((*MockRepo)(nil).RemoveMyAuth), ctx, auth)
}

// Signup mocks base method.
func (m *MockRepo) Signup(ctx context.Context, userID, name, email, password, secret, workspaceID string, mockAuth bool) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", ctx, userID, name, email, password, secret, workspaceID, mockAuth)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signup indicates an expected call of Signup.
func (mr *MockRepoMockRecorder) Signup(ctx, userID, name, email, password, secret, workspaceID, mockAuth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockRepo)(nil).Signup), ctx, userID, name, email, password, secret, workspaceID, mockAuth)
}

// SignupNoID mocks base method.
func (m *MockUserRepos) SignupNoID(ctx context.Context, name, email, password, secret string, mockAuth bool) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignupNoID", ctx, name, email, password, secret, mockAuth)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignupNoID indicates an expected call of SignupNoID.
func (mr *MockUserReposMockRecorder) SignupNoID(ctx, name, email, password, secret, mockAuth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignupNoID", reflect.TypeOf((*MockUserRepos)(nil).SignupNoID), ctx, name, email, password, secret, mockAuth)
}

// SignupOIDC mocks base method.
func (m *MockRepo) SignupOIDC(ctx context.Context, name, email, sub, secret string) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignupOIDC", ctx, name, email, sub, secret)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignupOIDC indicates an expected call of SignupOIDC.
func (mr *MockRepoMockRecorder) SignupOIDC(ctx, name, email, sub, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignupOIDC", reflect.TypeOf((*MockRepo)(nil).SignupOIDC), ctx, name, email, sub, secret)
}

// StartPasswordReset mocks base method.
func (m *MockRepo) StartPasswordReset(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartPasswordReset", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartPasswordReset indicates an expected call of StartPasswordReset.
func (mr *MockRepoMockRecorder) StartPasswordReset(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartPasswordReset", reflect.TypeOf((*MockRepo)(nil).StartPasswordReset), ctx, email)
}

// Update mocks base method.
func (m *MockRepo) Update(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepoMockRecorder) Update(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepo)(nil).Update), ctx, name)
}

// UpdateMe mocks base method.
func (m *MockRepo) UpdateMe(ctx context.Context, input user.UpdateMeInput) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMe", ctx, input)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMe indicates an expected call of UpdateMe.
func (mr *MockRepoMockRecorder) UpdateMe(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMe", reflect.TypeOf((*MockRepo)(nil).UpdateMe), ctx, input)
}

// VerifyUser mocks base method.
func (m *MockRepo) VerifyUser(ctx context.Context, code string) (*user0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUser", ctx, code)
	ret0, _ := ret[0].(*user0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyUser indicates an expected call of VerifyUser.
func (mr *MockRepoMockRecorder) VerifyUser(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUser", reflect.TypeOf((*MockRepo)(nil).VerifyUser), ctx, code)
}
