// Code generated by MockGen. DO NOT EDIT.
// Source: ./workspace.go
//
// Generated by this command:
//
//	mockgen -source=./workspace.go -destination=./mock_repo/mock_workspace.go -package mock_repo
//

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	context "context"
	reflect "reflect"

	repo "github.com/reearth/reearth-accounts/server/internal/usecase/repo"
	user "github.com/reearth/reearth-accounts/server/pkg/user"
	workspace "github.com/reearth/reearth-accounts/server/pkg/workspace"
	usecasex "github.com/reearth/reearthx/usecasex"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkspace is a mock of Workspace interface.
type MockWorkspace struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceMockRecorder
	isgomock struct{}
}

// MockWorkspaceMockRecorder is the mock recorder for MockWorkspace.
type MockWorkspaceMockRecorder struct {
	mock *MockWorkspace
}

// NewMockWorkspace creates a new mock instance.
func NewMockWorkspace(ctrl *gomock.Controller) *MockWorkspace {
	mock := &MockWorkspace{ctrl: ctrl}
	mock.recorder = &MockWorkspaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspace) EXPECT() *MockWorkspaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkspace) Create(arg0 context.Context, arg1 *workspace.Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWorkspaceMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkspace)(nil).Create), arg0, arg1)
}

// Filtered mocks base method.
func (m *MockWorkspace) Filtered(arg0 repo.WorkspaceFilter) repo.Workspace {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filtered", arg0)
	ret0, _ := ret[0].(repo.Workspace)
	return ret0
}

// Filtered indicates an expected call of Filtered.
func (mr *MockWorkspaceMockRecorder) Filtered(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filtered", reflect.TypeOf((*MockWorkspace)(nil).Filtered), arg0)
}

// FindByAlias mocks base method.
func (m *MockWorkspace) FindByAlias(ctx context.Context, alias string) (*workspace.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAlias", ctx, alias)
	ret0, _ := ret[0].(*workspace.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAlias indicates an expected call of FindByAlias.
func (mr *MockWorkspaceMockRecorder) FindByAlias(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAlias", reflect.TypeOf((*MockWorkspace)(nil).FindByAlias), ctx, alias)
}

// FindByID mocks base method.
func (m *MockWorkspace) FindByID(arg0 context.Context, arg1 workspace.ID) (*workspace.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*workspace.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockWorkspaceMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockWorkspace)(nil).FindByID), arg0, arg1)
}

// FindByIDs mocks base method.
func (m *MockWorkspace) FindByIDs(arg0 context.Context, arg1 workspace.IDList) (workspace.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", arg0, arg1)
	ret0, _ := ret[0].(workspace.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockWorkspaceMockRecorder) FindByIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockWorkspace)(nil).FindByIDs), arg0, arg1)
}

// FindByIntegration mocks base method.
func (m *MockWorkspace) FindByIntegration(arg0 context.Context, arg1 workspace.IntegrationID) (workspace.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIntegration", arg0, arg1)
	ret0, _ := ret[0].(workspace.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIntegration indicates an expected call of FindByIntegration.
func (mr *MockWorkspaceMockRecorder) FindByIntegration(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIntegration", reflect.TypeOf((*MockWorkspace)(nil).FindByIntegration), arg0, arg1)
}

// FindByIntegrations mocks base method.
func (m *MockWorkspace) FindByIntegrations(arg0 context.Context, arg1 workspace.IntegrationIDList) (workspace.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIntegrations", arg0, arg1)
	ret0, _ := ret[0].(workspace.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIntegrations indicates an expected call of FindByIntegrations.
func (mr *MockWorkspaceMockRecorder) FindByIntegrations(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIntegrations", reflect.TypeOf((*MockWorkspace)(nil).FindByIntegrations), arg0, arg1)
}

// FindByName mocks base method.
func (m *MockWorkspace) FindByName(arg0 context.Context, arg1 string) (*workspace.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", arg0, arg1)
	ret0, _ := ret[0].(*workspace.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockWorkspaceMockRecorder) FindByName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockWorkspace)(nil).FindByName), arg0, arg1)
}

// FindByUser mocks base method.
func (m *MockWorkspace) FindByUser(arg0 context.Context, arg1 user.ID) (workspace.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUser", arg0, arg1)
	ret0, _ := ret[0].(workspace.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUser indicates an expected call of FindByUser.
func (mr *MockWorkspaceMockRecorder) FindByUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUser", reflect.TypeOf((*MockWorkspace)(nil).FindByUser), arg0, arg1)
}

// FindByUserWithPagination mocks base method.
func (m *MockWorkspace) FindByUserWithPagination(ctx context.Context, id user.ID, pagination *usecasex.Pagination) (workspace.List, *usecasex.PageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserWithPagination", ctx, id, pagination)
	ret0, _ := ret[0].(workspace.List)
	ret1, _ := ret[1].(*usecasex.PageInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserWithPagination indicates an expected call of FindByUserWithPagination.
func (mr *MockWorkspaceMockRecorder) FindByUserWithPagination(ctx, id, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserWithPagination", reflect.TypeOf((*MockWorkspace)(nil).FindByUserWithPagination), ctx, id, pagination)
}

// Remove mocks base method.
func (m *MockWorkspace) Remove(arg0 context.Context, arg1 workspace.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWorkspaceMockRecorder) Remove(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWorkspace)(nil).Remove), arg0, arg1)
}

// RemoveAll mocks base method.
func (m *MockWorkspace) RemoveAll(arg0 context.Context, arg1 workspace.IDList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockWorkspaceMockRecorder) RemoveAll(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockWorkspace)(nil).RemoveAll), arg0, arg1)
}

// Save mocks base method.
func (m *MockWorkspace) Save(arg0 context.Context, arg1 *workspace.Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockWorkspaceMockRecorder) Save(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockWorkspace)(nil).Save), arg0, arg1)
}

// SaveAll mocks base method.
func (m *MockWorkspace) SaveAll(arg0 context.Context, arg1 workspace.List) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAll", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAll indicates an expected call of SaveAll.
func (mr *MockWorkspaceMockRecorder) SaveAll(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAll", reflect.TypeOf((*MockWorkspace)(nil).SaveAll), arg0, arg1)
}
