// Code generated by MockGen. DO NOT EDIT.
// Source: ./role.go
//
// Generated by this command:
//
//	mockgen -source=./role.go -destination=./mock_role.go -package role
//

// Package role is a generated GoMock package.
package role
