name: deploy-cerbos
on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy-to-cloud-run:
    name: Deploy to Cloud Run (Nightly)
    needs:  build-and-push-docker-image
    runs-on: ubuntu-latest
    if: ${{ inputs.name == 'nightly' }}
    env:
      IMAGE: us-central1-docker.pkg.dev/reearth-oss/reearth/cerbos:nightly
      GCP_REGION: us-central1
      CLOUD_RUN_SERVICE: cerbos
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_REEARTH_OSS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Deploy to Cloud Run for cerbos
        run: |
          gcloud run deploy $CLOUD_RUN_SERVICE \
            --image $IMAGE \
            --region $GCP_REGION \
            --platform managed \
            --port 3593 \
            --quiet
