name: build-server
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true
jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: reearth/reearth-dashboard-api:nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./server
          platforms: linux/amd64
          load: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
      # - name: Save docker image
      #   run: docker save ${{ env.IMAGE_NAME }} | gzip > reearth-dashboard-api-docker.tar.gz
      # - name: Save imaged to artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: reearth-dashboard-api-docker
      #     path: reearth-dashboard-api-docker.tar.gz
      #     if-no-files-found: error
