name: build-server
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true
jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/reearth/reearth-account:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and load docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          platforms: linux/amd64
          load: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      - name: Save docker image
        run: docker save ${{ env.IMAGE_NAME }} | gzip > reearth-account-docker.tar.gz
      - name: Save imaged to artifact
        uses: actions/upload-artifact@v4
        with:
          name: reearth-account-docker
          path: reearth-account-docker.tar.gz
          if-no-files-found: error
