name: build-deploy-server
on:
  workflow_call:
    inputs:
      sha_short:
        required: true
        type: string
      new_tag:
        required: true
        type: string
      new_tag_short:
        required: true
        type: string
      name:
        required: true
        type: string
      sha:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-push-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    if: ${{ inputs.name != 'blank' || inputs.new_tag != 'blank' }}
    env:
      IMAGE_NAME_GHCR_BASE: ghcr.io/eukarya-inc/reearth/reearth-dashboard-api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Build Options
        id: options
        run: |
          TAG="${{ inputs.new_tag_short != 'blank' && inputs.new_tag_short || '' }}"
          NAME="${{ inputs.name }}"
          SHA="${{ inputs.sha_short }}"

          if [[ -n "$TAG" ]]; then
            PLATFORMS="linux/amd64,linux/arm64"
            VERSION="$TAG"
            TAGS="$IMAGE_NAME_GHCR_BASE:$TAG"

            if [[ ! "$TAG" =~ '-' ]]; then
              TAGS+=",${IMAGE_NAME_GHCR_BASE}:${TAG%.*}"
              TAGS+=",${IMAGE_NAME_GHCR_BASE}:${TAG%%.*}"
              TAGS+=",${IMAGE_NAME_GHCR_BASE}:latest"
            fi
          else
            PLATFORMS="linux/amd64"
            VERSION="$SHA"
            TAGS="$IMAGE_NAME_GHCR_BASE:$NAME"
          fi

          echo "platforms=$PLATFORMS" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push Docker image for dashboard api
        uses: docker/build-push-action@v6
        with:
          context: ./server
          platforms: ${{ steps.options.outputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          build-args: VERSION=${{ steps.options.outputs.version }}
          tags: ${{ steps.options.outputs.tags }}

  deploy-to-cloud-run:
    name: Deploy to Cloud Run (Nightly)
    needs:  build-and-push-docker-image
    runs-on: ubuntu-latest
    if: ${{ inputs.name == 'nightly' }}
    env:
      IMAGE_NAME_GHCR: ghcr.io/eukarya-inc/reearth/reearth-dashboard-api:nightly
      IMAGE_NAME_GAR: us-central1-docker.pkg.dev/reearth-oss/reearth/reearth-dashboard-api:nightly
      GCP_REGION: us-central1
      CLOUD_RUN_SERVICE: reearth-dashboard-api
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_REEARTH_OSS }}

      - name: Configure docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Pull docker image from GitHub Container Registry
        run: docker pull $IMAGE_NAME_GHCR

      - name: Tag docker image for Google Cloud Artifact Registry
        run: docker tag $IMAGE_NAME_GHCR $IMAGE_NAME_GAR

      - name: Push docker image to Google Cloud Artifact Registry
        run: docker push $IMAGE_NAME_GAR

      - name: Update Migration Job
        run: |
          gcloud run jobs update migration-job \
            --image $IMAGE_NAME_GAR \
            --region $GCP_REGION \
            --set-env-vars="RUN_MIGRATION=true" \
            --quiet

      - name: Execute Migration Job
        run: |
          gcloud run jobs execute migration-job \
            --region $GCP_REGION \
            --wait \
            --quiet

      - name: Deploy to Cloud Run for dashboard api (Nightly)
        run: |
          gcloud run deploy $CLOUD_RUN_SERVICE \
            --image $IMAGE_NAME_GAR \
            --region $GCP_REGION \
            --platform managed \
            --quiet
