name: build-server
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true
jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME_DASHBOARD_API: reearth/reearth-dashboard-api:nightly
      IMAGE_NAME_CERBOS: reearth/cerbos:nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image for dashboard api
        uses: docker/build-push-action@v3
        with:
          context: ./server
          platforms: linux/amd64
          load: true
          tags: ${{ env.IMAGE_NAME_DASHBOARD_API }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
      - name: Build and push Docker image for Cerbos
        uses: docker/build-push-action@v3
        with:
          context: ./cerbos
          platforms: linux/amd64
          load: true
          tags: ${{ env.IMAGE_NAME_CERBOS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
