name: ci-server
on:
  workflow_call:
env:
  GO_VERSION: "1.20"
jobs:
  ci-server-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
          working-directory: server
          args: --timeout=5m
  ci-server-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5-focal
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: server/go.sum
      - name: Setup Cerbos
        uses: cerbos/cerbos-setup-action@v1
        with:
          version: latest
      - name: Run tests with Cerbos server
        run: cerbos run -- go test ./server/... -v -race
        env:
          REEARTH_DB: mongodb://localhost
          CERBOS_HOST: localhost:3593
