name: deploy-server-dev
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
env:
  IMAGE_DASHBOARD_API: reearth/reearth-dashboard-api:nightly
  IMAGE_GCP_DASHBOARD_API: us-central1-docker.pkg.dev/reearth-oss/reearth/reearth-dashboard-api:nightly
  IMAGE_CERBOS: reearth/cerbos:nightly
  IMAGE_GCP_CERBOS: us-central1-docker.pkg.dev/reearth-oss/reearth/cerbos:nightly
  GCP_REGION: asia-northeast1
jobs:
  deploy_test:
    name: Deploy app to test env
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'reearth/reearth-dashboard'
    steps:
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Configure docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: docker push for dashboard api
        run: |
          docker pull $IMAGE_DASHBOARD_API
          docker tag $IMAGE_DASHBOARD_API $IMAGE_GCP_DASHBOARD_API
          docker push $IMAGE_GCP_DASHBOARD_API
      - name: docker push for cerbos
        run: |
          docker pull $IMAGE_CERBOS
          docker tag $IMAGE_CERBOS $IMAGE_GCP_CERBOS
          docker push $IMAGE_GCP_CERBOS
      - name: Deploy to Cloud Run for dashboard api
        run: |
          gcloud run deploy reearth-dashboard-api \
            --image $IMAGE_GCP_DASHBOARD_API \
            --region $GCP_REGION \
            --platform managed \
            --quiet
      - name: Deploy to Cloud Run for cerbos
        run: |
          gcloud run deploy cerbos \
            --image $IMAGE_GCP_CERBOS \
            --region $GCP_REGION \
            --platform managed \
            --quiet

